name: Generate Artifact Python

env:
    ARTIFACT_NAME: pythonartifact

on: [workflow_call]

jobs:
    on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/upload-artifact@v4 
              with:
               name: ${{ env.ARTIFACT_NAME }}
               path: .