name: CodeVitals Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-vitals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install --save-dev code-vitals
      - run: code-v deps
      - run: code-v code
