name: Test Py Script

on: [push]

jobs:
    main:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
          with:
           name: pyfile
           path: ./hello.py

    publish:
        needs: main
        uses: ./.github/workflows/artifactpy.yml
        secrets: inherit