name: Test Py Script

on: [push]

jobs:
    main:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Running Script
          run: python3 ./hello.py 
        - name: Build
          run: ./artifactpy.py
